### ISSUE TITLE
YAML - Syntax Coloring - Block Styles

### ISSUE THREAD

**Issue by dfelton** [eclipse/tm4e#404] opened 2022-05-30 03:55 UTC
Formatting appears to have some odd behavior for [block styles](https://yaml.org/spec/1.2.2/#chapter-8-block-style-productions). In my testing it impacted both [literal](https://yaml.org/spec/1.2.2/#literal-style) and [folded](https://yaml.org/spec/1.2.2/#813-folded-style), all three [chomping indicators](https://yaml.org/spec/1.2.2/#8112-block-chomping-indicator).

<img width="761" alt="Screen Shot 2022-05-29 at 10 53 39 PM" src="https://user-images.githubusercontent.com/2659558/170914234-61fbe454-d78d-4bd7-b252-e9b8dbe0a54b.png">

YAML to reproduce the above:

```yaml
---
- name: Wild Web Developer HTML, CSS, JSON, Yaml, JavaScript, TypeScript, Node tools
  version: 0.10.14.202205271506
  id: org.eclipse.wildwebdeveloper.feature.feature.group
  bug_report:
    - name: Block Style
      see_more: https://yaml.org/spec/1.2.2/#chapter-8-block-style-productions
      example: |
        #!/bin/bash
        [ 1 -eq 1 ]; echo foo # foo
        [ 1 -eq 1 ] && echo foo # foo
        [ 1 -eq 1 ] && >&1 echo foo # foo
        [ 1 -eq 1 ] && >&1 echo foo || echo foo # foo
        [ 1 -eq 1 ] && >&1 echo foo && echo foo # foo
        [ ! 1 -eq 0 ] || echo foo || echo foo && echo foo 2>&1 # foo
        [ ! 1 -eq 0 ] || >&1 echo foo # foo
        [ ! 1 -eq 1 ]; echo foo 
        [ 1 -eq 1 ] && echo foo
        { echo foo }
        ( echo foo )
        ( /bin/true ) && echo foo
        ( ! /bin/false ) >&2 echo foo
        [[ ! "" != "" ]] || echo foo
        [[ ! "" == "" ]] && echo foo
        if [ 1 -eq 1 ]; then echo foo && echo foo; fi
        [[ "foo" == "foo" ]] && >&2 echo foo
        echo -n 'this causes a large formatting
        issue to begin 
        '
        echo the editor now thinks we are still residing within that same string
        [ 1 -eq 1 ]; echo foo # foo
        [ 1 -eq 1 ] && echo foo # foo
        [ 1 -eq 1 ] && >&1 echo foo # foo
        [ 1 -eq 1 ] && >&1 echo foo || echo foo # foo
        [ 1 -eq 1 ] && >&1 echo foo && echo foo # foo
        [ ! 1 -eq 0 ] || echo foo || echo foo && echo foo 2>&1 # foo
        [ ! 1 -eq 0 ] || >&1 echo foo # foo
        [ ! 1 -eq 1 ]; echo foo 
        [ 1 -eq 1 ] && echo foo
        { echo foo }
        ( echo foo )
        ( /bin/true ) && echo foo
        ( ! /bin/false ) >&2 echo foo
      this_color: is_incorrect

    - name: Another Item
      see_more: https://yaml.org/spec/1.2.2/#chapter-8-block-style-productions
...
```

**Comment by mickaelistria** [comment] 2022-05-30 07:29
Syntax highlighting is provided to Eclipse TM4E project. I transferred the issue accordingly.
Can you please try installing latest release of TM4E as described on https://github.com/eclipse/tm4e#in-eclipse-ide-or-rcp-applications ? I don't reproduce the issue on my machine with a recent build.

**Comment by dfelton** [comment] 2022-06-01 04:28
> Can you please try installing latest release of TM4E

@mickaelistria certainly. I'll provide an update as soon as I can. It may be a week here or so but I'll certainly get back to this.

Thank you.

**Comment by dfelton** [comment] 2022-06-01 21:28
So, thus far I have done the following:

- Switched back from Dark Theme to Light
  - 
- Checked for new updates in Eclipse, and upgraded everything which was available to be upgraded.
  - Restarted Eclipse and reviewed the syntax highlighting (same results as before)
  - For what it is worth, my Eclipse Version is currently `2022-03 (4.23.0)`, Build ID `20220310-1457`.

---

- Installed TM4E by adding it to the "Available Sites".
  - Installed "TextMate" and "Dependencies"
  - Restarted Eclipse
- Once I opened eclipse up again, I discovered that I had lost the configured text editor for `*.yml` files. Upon first opening my file(s) up Eclipse prompted me asking if I had wanted to search the marketplace.
  - While my memory here is vague, I believe prior to Eclipse+Wild Web Developer was using "Generic Text Editor" for these (no specific "YAML" editor available in list now or prior to).
  - Attempting both "Text Editor" and "Generic Text Editor", I have completely lost all formatting (in light theme the background is white and all text is black)
- At this time I then went back and also installed "Sources" from TM4E
  - Restarted Eclipse, Checked again and still no formatting

---

At this point, I have the following questions / suspicions:

- What is the "Editor" you guys are using when opening yaml files? (For example, manually done by right clicking file -> "Open With")
- Possibly I am using too old of a version of Eclipse? I'm willing to install latest, haven't checked at time of writing what that may be
- Last thought, I feel there must still be something lacking here at Wild Web Developer's end, as from the very README.md doc of TM4E:

> You can install tm4e with the update site https://download.eclipse.org/tm4e/snapshots/. TM4E is usually installed together with its consumers, so end-user should usually not need to directly install it.

(this is what lead me to think maybe my Eclipse install is too old)

**Comment by sebthom** [comment] 2022-06-02 09:15
This are my plugin versions:
![image](https://user-images.githubusercontent.com/426959/171597639-b3cc4c77-7816-4b26-a753-a60e9494fc94.png)

**Comment by sebthom** [comment] 2022-07-01 20:42
@dfelton could you please try the new TM4E 0.6.0 release and check if this resolves your issue?

**Comment by sebthom** [comment] 2022-10-21 20:40
I am closing this issue for now. Since we cannot reproduce it with latest TM4E release. Feel free to reopen if needed.

**Closed by sebthom** 2022-10-21 20:40 UTC
Labels: bug
