### ISSUE TITLE
tme4.core from Maven

### ISSUE THREAD

**Issue by Sciss** [eclipse/tm4e#276] opened 2021-05-29 18:03 UTC
Hi there,

the readme says

> as a Java API with Maven
>
> [more information coming soon]

could you please post the repository (maven central?) and the group-id and artifact-id for this project; in particular I'd be interested to use the `core` package, I assume that is a separatedly published artefact?

**Comment by mickaelistria** [comment] 2021-05-31 07:01
At the moment, TM4E project doesn't publish the artifact to a Maven repository. Any contribution from anyone to make this happen would be welcome.
However, if you use the search.maven.org service and look for tm4e, you'll find some people did publish tm4e to central with their own groupId. So you could try to reuse those artifacts.

**Comment by sebthom** [comment] 2022-05-04 17:42
Duplicate of #83

**Closed by sebthom** 2022-05-04 17:42 UTC
Labels: duplicate
