### ISSUE TITLE
NPE in theme preferences

### ISSUE THREAD

**Issue by svenefftinge** [eclipse/tm4e#130] opened 2017-08-09 15:31 UTC
When trying to add another theme:

java.lang.NullPointerException
	at org.eclipse.tm4e.ui.internal.preferences.ThemePreferencePage$1.selectionChanged(ThemePreferencePage.java:217)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:155)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.ui.internal.JFaceUtil$$Lambda$8/1294605731.run(Unknown Source)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:152)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2180)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1223)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1252)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:240)
	at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:235)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:400)

**Comment by angelozerr** [comment] 2017-08-09 15:49
I don't understand you can have this error. Today you cannot add new theme. The "New" button should be disabled.

Today tm4e uses CSS to defines themes, but I would like to use TextMate theme (see https://github.com/eclipse/tm4e/issues/2). I have started to develop a TextMate theme parser (like VSCode) but now I must support tokenizeLine2  (like VSCode) (see https://github.com/eclipse/tm4e/issues/38)

It's a big work, I must find time to do that -(

**Comment by angelozerr** [comment] 2017-09-08 15:57
@svenefftinge could you tell me please how you can hav ethis error please. Thanks!

**Comment by svenefftinge** [comment] 2017-09-11 06:23
AFAIR, I simply opened the preferences and tried to change them.

**Comment by mickaelistria** [comment] 2019-09-05 11:20
I'm closing as cannot reproduce.
If you can reproduce it with latest snapshots, feel free to reopen with more details.

**Closed by mickaelistria** 2019-09-05 11:20 UTC
Labels: bug
