### ISSUE TITLE
Italic should not be applied inside words

### ISSUE THREAD

**Issue by PyvesB** [eclipse/tm4e#229] opened 2019-10-17 08:23 UTC
Hello there,

Hopefully this is the right place to report this bug. When displaying documentation hovers in LSP-based Eclipse plugins, I noticed that elements such as snake case variables are not rendered correctly, making them hard to read:
![Screenshot 2019-10-17 at 09 19 49](https://user-images.githubusercontent.com/10694593/66991124-5e1eb000-f0bf-11e9-92de-0f9be4ef55d6.png)

The markdown parser treats `_` characters within words as italic delimiters, but these should probably only be treated as such when surrounding a word, e.g. `_TEST_CONSTANT_UPPER_SNAKE_CASE_`.

Thanks for reading!

Pyves

**Comment by angelozerr** [comment] 2019-10-17 08:48
@PyvesB LSP4E manages their hover by using `org.eclipse.mylyn.wikitext.markdown` So it's not an issue for TM4E, but TM4E provides a markdown support (with github code syntax which highlight code by using TextMate grammar).

As @mickaelistria explained me, LSP4E don't want to have dependency from TM4E, but IMHO I think LSP4E should provide an extension point to customize hover processor and in this case we could use TM4E markdown support.

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=508824#c14

**Comment by mickaelistria** [comment] 2019-10-18 10:33
The issue is actually in Mylyn wikitext (which LSP4E is using).
Moving to TM4E markdown support would have some implications: mylyn wikitext is more stable and already has a more consequent maintainers community; it's still safer to use and cheaper to maintaiin. We can reconsider LSP4E using TM4E Markdown when this changes, but moving to it right now would be a form of new investment to take away from somewhere else.

**Comment by PyvesB** [comment] 2019-10-18 20:27
Okay, thanks for pointing me in the right direction. I have raised [bug 552231](https://bugs.eclipse.org/bugs/show_bug.cgi?id=552231) to report this. Unfortunately, Mylyn Wikitext does have quite a few issues (I saw you opened several bugs as well @mickaelistria), and there's not been any actual improvements to the markdown module since February 2017. 😕

**Comment by angelozerr** [comment] 2019-10-18 21:52
> The issue is actually in Mylyn wikitext (which LSP4E is using).
Moving to TM4E markdown support would have some implications: mylyn wikitext is more stable and already has a more consequent maintainers community; it's still safer to use and cheaper to maintaiin. 

I understand.

> We can reconsider LSP4E using TM4E Markdown when this changes, but moving to it right now would be a form of new investment to take away from somewhere else.

One of reason why I decided to implement markdown support (I ported the js markdwon library used in vscode in Java) in TM4E i sthat I wanted support syntax highlight which IMHO very important.

I use this markdown support in typescript.java. Here a sample with TypeScript completion (see the signatore of the method which is colorized by using TextMate):

![](https://user-images.githubusercontent.com/1932211/27551247-e6a3c38a-5aa2-11e7-8e54-f1343658c82b.png)

 I'm not sure wikitext will implement that one day since coloration can be done in several mean in Eclipse. 

> here's not been any actual improvements to the markdown module since February 2017. 

It's the second reason why I decided to implement my own markdown support.

**Comment by mickaelistria** [comment] 2019-10-19 16:08
I'll try evaluating the TM4E replacement to wikitext this winter.

**Comment by angelozerr** [comment] 2019-10-19 16:52
> I'll try evaluating the TM4E replacement to wikitext for LSP4E this winter.

Cool:) I think it should be improved again and I implemented super quickly. And there are no tests, but I had the same renderer than vscode (with sample that I tried).

If you think it's a good idea to use the TM4E markdown support, we need to write tests and support other thing like table if we need it (If I remember, it's not supported).

**Comment by PyvesB** [comment] 2019-10-19 17:21
Maybe it's also worth looking around if there aren't any other markdown Java libraries that TM4E could integrate with? It would reduce maintenance effort and avoid effort duplication.

**Comment by mickaelistria** [comment] 2019-11-20 17:02
Closing here are it's reported (and being fixed) in TM4E.

**Closed by mickaelistria** 2019-11-20 17:02 UTC

**Comment by PyvesB** [comment] 2019-11-20 22:40
I've submitted a couple of patches to Mylyn Wikitext:
https://git.eclipse.org/r/c/153004/
https://git.eclipse.org/r/c/153093/

This should hopefully address some of the most outstanding issues (including this one) but also improves things for other projects relying on Mylyn Wikitext, including the Markdown editor in the IDE itself.
