### ISSUE TITLE
Use TextMate theme to colorize textmate grammar

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#2] opened 2016-11-04 12:58 UTC

**Comment by mickaelistria** [comment] 2022-06-07 21:51
Done a while ago.

**Comment by sebthom** [comment] 2024-02-11 18:20
This has not yet been implemented. Currently only CSS Themes are supported.

**Comment by sebthom** [comment] 2024-02-11 18:20
Ah well, duplicate of #255

**Closed by sebthom** 2024-02-11 18:20 UTC
Labels: enhancement
