### ISSUE TITLE
Argument not valid error when formatting JSON

### ISSUE THREAD

**Issue by PyvesB** [eclipse/tm4e#236] opened 2019-12-09 17:22 UTC
Hi there!

I'm using TM4E through the JSON language server shipped with Wild Web Developer.

Consider the following JSON:
```
    [
        { "key1": "value1",
        "keys2" }
    ]
```

Note that this is not yet valid JSON at this point in time.

Formatting the file works fine, however, a TM4E error pops up in the Error Log:
```
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4701)
	at org.eclipse.swt.SWT.error(SWT.java:4635)
	at org.eclipse.swt.SWT.error(SWT.java:4606)
	at org.eclipse.swt.custom.StyledText.setStyleRanges(StyledText.java:10256)
	at org.eclipse.swt.custom.StyledText.replaceStyleRanges(StyledText.java:8007)
	at org.eclipse.jface.text.TextViewer.addPresentation(TextViewer.java:4693)
	at org.eclipse.jface.text.TextViewer.changeTextPresentation(TextViewer.java:4770)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.applyTextRegionCollection(TMPresentationReconciler.java:694)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.colorize(TMPresentationReconciler.java:589)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.textChanged(TMPresentationReconciler.java:314)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2709)
	at org.eclipse.jface.text.TextViewer.fireRedrawChanged(TextViewer.java:4915)
	at org.eclipse.jface.text.TextViewer.enabledRedrawing(TextViewer.java:4955)
	at org.eclipse.jface.text.TextViewer.enabledRedrawing(TextViewer.java:4923)
	at org.eclipse.jface.text.TextViewer.setRedraw(TextViewer.java:5005)
	at org.eclipse.jface.text.TextViewer.setRedraw(TextViewer.java:4979)
	at org.eclipse.jface.text.TextViewer$RewriteTarget.setRedraw(TextViewer.java:1000)
	at org.eclipse.jface.text.TextViewer$DocumentRewriteSessionListener.documentRewriteSessionChanged(TextViewer.java:1392)
	at org.eclipse.jface.text.AbstractDocument.fireRewriteSessionChanged(AbstractDocument.java:1440)
	at org.eclipse.jface.text.AbstractDocument.stopRewriteSession(AbstractDocument.java:1521)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.stopRewriteSession(SynchronizableDocument.java:108)
	at org.eclipse.jface.text.RewriteSessionEditProcessor.performEdits(RewriteSessionEditProcessor.java:101)
	at org.eclipse.lsp4e.LSPEclipseUtils.applyEdits(LSPEclipseUtils.java:350)
	at org.eclipse.lsp4e.operations.format.LSPFormatter.applyEdits(LSPFormatter.java:44)
	at org.eclipse.lsp4e.operations.format.LSPFormatHandler.lambda$1(LSPFormatHandler.java:47)
	at org.eclipse.lsp4e.operations.format.LSPFormatHandler$$Lambda$1615.00000000681B5820.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4145)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3812)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.ui.internal.Workbench$$Lambda$107.0000000000000000.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```

Note that I'm using TM4E 0.3.4 on Eclipse 2019-12 RC1, with a macOS machine.

Let me know if you need any additional information!

**Comment by mickaelistria** [comment] 2019-12-10 08:10
I couldn't reproduce it locally. Can you please try TM4E 0.4.0 from latest snapshot or release p2 repo (both are identical at the moment, but since you're closely following the Generic Editor/TextMate stack, I suggest you use the snapshots in your development IDE so you'll spot issues and fixes more immediately)

**Comment by PyvesB** [comment] 2019-12-10 09:16
Same problem with latest 0.4.0. However, I tried reproducing on my Windows machine yesterday evening, but I didn't have any problems. May be a macOS-only issue.

**Comment by mickaelistria** [comment] 2019-12-10 09:17
this stack is interesting though, even if it's hard to reproduce. If you can provide a patch to just place the necessary guards where most appropriate to avoid this error, that'd be welcome.

**Comment by PyvesB** [comment] 2019-12-10 09:56
Not sure when/if I'll get round to attempting a fix. My macOS is my work machine, I don't tend to use it for Eclipse development, mostly beta testing.

**Comment by mickaelistria** [comment] 2019-12-12 08:58
This can be the result of a (temporary) unsynchronization between: the widget content, the model (document) and TM4E style proposals.
I've tried looking in the code and there aren't much guards in JFace for that, and implementing the right guards in TM4E wouldn't be -as we're not even sure widget and model document are sync'd when the error happens-.
As far as I understand, this issue "only" causes a log message and fails the current styling session, but doesn't prevent from further usage. Editing the file progressively restore the styles. Doesn't it?
If so, I think I'll just leave things as it and won't investigate more. However, any assistance, further analysis or patch would be welcome ;)

**Comment by PyvesB** [comment] 2019-12-12 20:05
> As far as I understand, this issue "only" causes a log message and fails the current styling session, but doesn't prevent from further usage.

Yes, that is correct.

Will let you know if I come up with any additional observations or ways to reproduce on other operating systems.

**Comment by weissets** [comment] 2020-01-31 16:52
I can reproduce this error frequently on Windows10. We are using LSP4E in combination with TM4E.
We have an editor which replaces its contents frequently according to its input. This issue always appears if the first line in the text editor for the new input is shorter (i.e. has fewer characters) than the first line of the previous input.

Example:
Previous content:
```
MyLongClass MyLongName {
   ...
}
```
New content:
```
MyClass MyName {
   ...
}
```

The calculation of the style ranges still tries to calculate the '{' of the old input and TMPresentationReconciler#getTokenLengh() return with a negative range which then leads to the exception in SWT. For me it seems like the tokenizer and the document are not in sync anymore or working on different documents.

SyntaxHighlighting is working even with the Exception, but all the Error Log entries are really annoying. 

Hope this helps you guys hunting this bug down...

**Comment by sebthom** [comment] 2022-05-12 19:44
@PyvesB @weissets can you please try with the latest release of tm4e. if the issue still occurs please provide a new stacktrace. if not please also report back so we can close the issue. thanks!

**Comment by PyvesB** [comment] 2022-05-13 09:07
The problem still occurs with tm4e 0.4.6.202205121950:
```
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4899)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.custom.StyledText.setStyleRanges(StyledText.java:10649)
	at org.eclipse.swt.custom.StyledText.replaceStyleRanges(StyledText.java:8239)
	at org.eclipse.jface.text.TextViewer.addPresentation(TextViewer.java:4773)
	at org.eclipse.jface.text.TextViewer.changeTextPresentation(TextViewer.java:4850)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.applyTextRegionCollection(TMPresentationReconciler.java:724)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.colorize(TMPresentationReconciler.java:612)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.textChanged(TMPresentationReconciler.java:342)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2785)
	at org.eclipse.jface.text.TextViewer.fireRedrawChanged(TextViewer.java:4995)
	at org.eclipse.jface.text.TextViewer.enabledRedrawing(TextViewer.java:5035)
	at org.eclipse.jface.text.TextViewer.enabledRedrawing(TextViewer.java:5003)
	at org.eclipse.jface.text.TextViewer.setRedraw(TextViewer.java:5085)
	at org.eclipse.jface.text.TextViewer.setRedraw(TextViewer.java:5059)
	at org.eclipse.jface.text.TextViewer$RewriteTarget.setRedraw(TextViewer.java:1004)
	at org.eclipse.jface.text.TextViewer$DocumentRewriteSessionListener.documentRewriteSessionChanged(TextViewer.java:1410)
	at org.eclipse.jface.text.AbstractDocument.fireRewriteSessionChanged(AbstractDocument.java:1432)
	at org.eclipse.jface.text.AbstractDocument.stopRewriteSession(AbstractDocument.java:1513)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.stopRewriteSession(SynchronizableDocument.java:108)
	at org.eclipse.jface.text.RewriteSessionEditProcessor.performEdits(RewriteSessionEditProcessor.java:101)
	at org.eclipse.lsp4e.LSPEclipseUtils.applyEdits(LSPEclipseUtils.java:436)
	at org.eclipse.lsp4e.operations.format.LSPFormatter.applyEdits(LSPFormatter.java:44)
	at org.eclipse.lsp4e.operations.format.LSPFormatHandler.lambda$1(LSPFormatHandler.java:55)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4320)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3943)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

It also happens when I select the shared snippet and shift tab to move it to the left.

**Comment by sebthom** [comment] 2022-06-01 17:11
I cannot reproduce this with the latest snapshot version. So it might be fixed now as a side effect of some other changes.

**Comment by PyvesB** [comment] 2022-06-02 07:45
Hmmm... I no longer seem to be able to install the latest snapshots. Here's the error I'm getting:
```
An error occurred while collecting items to be installed
session context was:(profile=_Users_py_eclipse_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.tm4e.languageconfiguration,0.4.2.202206020704
No repository found containing: osgi.bundle,org.eclipse.tm4e.ui,0.5.2.202206020704
No repository found containing: org.eclipse.update.feature,org.eclipse.tm4e.feature,0.4.6.202206020704
```

**Comment by akurtakov** [comment] 2022-06-02 07:49
Are you running Java 11? Could it be the fact that tm4e requires Java 17 now? The error looks really weird but this is what I first came to my mind .

**Comment by PyvesB** [comment] 2022-06-02 08:04
I'm running Java 18. Restarting Eclipse seemed to have solve the installation problem. I hate it when these kings of intermittent failures happen.

The error on format seem to have gone away. However, I still get a similar stack trace when pasting the same snippet and using Shift + Tab/Tab to shift the 4 lines of Json to the left and to the right:
```
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4899)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.custom.StyledText.setStyleRanges(StyledText.java:10651)
	at org.eclipse.swt.custom.StyledText.replaceStyleRanges(StyledText.java:8239)
	at org.eclipse.jface.text.TextViewer.addPresentation(TextViewer.java:4773)
	at org.eclipse.jface.text.TextViewer.changeTextPresentation(TextViewer.java:4850)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.applyTextRegionCollection(TMPresentationReconciler.java:688)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.colorize(TMPresentationReconciler.java:592)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.textChanged(TMPresentationReconciler.java:335)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2785)
	at org.eclipse.jface.text.TextViewer.fireRedrawChanged(TextViewer.java:4995)
	at org.eclipse.jface.text.TextViewer.enabledRedrawing(TextViewer.java:5035)
	at org.eclipse.jface.text.TextViewer.enabledRedrawing(TextViewer.java:5003)
	at org.eclipse.jface.text.TextViewer.setRedraw(TextViewer.java:5085)
	at org.eclipse.jface.text.TextViewer.setRedraw(TextViewer.java:5059)
	at org.eclipse.jface.text.TextViewer$RewriteTarget.setRedraw(TextViewer.java:1004)
	at org.eclipse.jface.text.TextViewer$DocumentRewriteSessionListener.documentRewriteSessionChanged(TextViewer.java:1410)
	at org.eclipse.jface.text.AbstractDocument.fireRewriteSessionChanged(AbstractDocument.java:1432)
	at org.eclipse.jface.text.AbstractDocument.stopRewriteSession(AbstractDocument.java:1513)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.stopRewriteSession(SynchronizableDocument.java:108)
	at org.eclipse.jface.text.TextViewer.shift(TextViewer.java:4355)
	at org.eclipse.jface.text.TextViewer.doOperation(TextViewer.java:3960)
	at org.eclipse.jface.text.source.SourceViewer.doOperation(SourceViewer.java:1064)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.doOperation(ProjectionViewer.java:1466)
	at org.eclipse.ui.internal.genericeditor.ExtensionBasedTextEditor$1.doOperation(ExtensionBasedTextEditor.java:109)
	at org.eclipse.ui.texteditor.ShiftAction.lambda$0(ShiftAction.java:87)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.texteditor.ShiftAction.run(ShiftAction.java:87)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ActivationCodeTrigger.verifyKey(AbstractTextEditor.java:785)
	at org.eclipse.jface.text.TextViewer$VerifyKeyListenersManager.verifyKey(TextViewer.java:480)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:70)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4579)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6248)
	at org.eclipse.swt.custom.StyledText.lambda$28(StyledText.java:5932)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4579)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1561)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1557)
	at org.eclipse.swt.widgets.Canvas.sendKeyEvent(Canvas.java:522)
	at org.eclipse.swt.widgets.Control.doCommandBySelector(Control.java:1085)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6428)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSResponder.interpretKeyEvents(NSResponder.java:59)
	at org.eclipse.swt.widgets.Composite.keyDown(Composite.java:607)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6260)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:236)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2162)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2487)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6380)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5628)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5767)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:117)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3938)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by mickaelistria** [comment] 2022-06-02 08:13
> The error on format seem to have gone away

OK thanks, let's close.

> I still get a similar stack trace when pasting the same snippet and using Shift + Tab/Tab to shift the 4 lines of Json to the left and to the right

Can you please open a separate ticket for this one?

**Closed by mickaelistria** 2022-06-02 08:13 UTC
Labels: bug
